---
- hosts: dev
  become: True
  tasks:
    - name: Launching the container
      docker_container:
        name: react-app
        image: "dockersandheep/react-pipe:v1.8"
        state: started
        published_ports:
          - 0.0.0.0:3000:3000
