---
- hosts: dev
  become: True
  tasks:
    - name: Launching the container
      docker_container:
        name: hariapp
        image: "dockersandheep/jenkins-ansible:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
